export const site = {
  name: "Matias Guajardo Palacios",
  shortName: "Matias Guajardo",
  initials: "MGP",
  role: "Desarrollador Full Stack",
  aspiration: "Arquitecto de Software",
  tagline:
    "Construyo productos web robustos y elegantes: de la lógica del backend al detalle del frontend, en camino hacia la arquitectura de software.",
  description:
    "Portafolio de Matias Guajardo Palacios, Desarrollador Full Stack e Ingeniero en Informática Empresarial (Universidad de Talca). Especializado en refactorización de sistemas legados, arquitectura SaaS multi-tenant e integración de bases de datos relacionales.",
  basePath: "/portfolio",
  url: "https://misterguajardo.github.io/portfolio",
  github: "https://github.com/MisterGuajardo",
  githubHandle: "MisterGuajardo",
  linkedin: "https://www.linkedin.com/in/m-i-g-p",
  email: "guajardomip@gmail.com",
  location: "Retiro, Chile",
  availableFor: "Remoto, híbrido o presencial",
  keywords: [
    "Matias Guajardo Palacios",
    "Desarrollador Full Stack",
    "Arquitecto de Software",
    "NestJS",
    "Angular",
    "TypeScript",
    "PostgreSQL",
    "Oracle DB",
    "Ingeniero en Informática Empresarial",
    "Portafolio",
    "Desarrollador Web Chile",
  ],
} as const;
